// Controlled, multilingual concept vocabulary.
//
// One line per concept:  id | parents | en | fr | de | es | it | pt | ja | zh
// Aliases are comma-separated, written naturally (case and accents are folded when loaded) and
// may be several words ("mount fuji", "coucher de soleil"). The id itself is always an alias.
// Parents give the hierarchy used for expansion ("kitten" → cat → animal).
//
// The vocabulary maps what people type ("chat", "Katze", "猫") and what authors and the VLM write
// ("kitty", "cats") onto one canonical id that is stored per artwork (artwork_concepts) and
// matched at query time. Extend it from GET /admin/queries (zero-result queries), then run
// `scripts/admin.sh reindex-all '"concepts"'` — no AI is involved, it is cheap.

export const VOCAB_TSV = `
animal | | animal,animals,creature,creatures,beast | animal,animaux,bete,betes | tier,tiere | animal,animales | animale,animali | animal,animais | 動物 | 动物
pet | animal | pet,pets | animal de compagnie | haustier,haustiere | mascota,mascotas | animale domestico | animal de estimacao | ペット | 宠物
cat | pet,animal | cat,cats,kitten,kittens,kitty,kitties,tabby,maine coon | chat,chats,chaton,chatons,minou | katze,katzen,kater,katzchen,mieze | gato,gatos,gatito,gatitos | gatto,gatti,gattino,micio | gato,gatos,gatinho | 猫,ねこ,ネコ,子猫 | 猫,貓,小猫
dog | pet,animal | dog,dogs,puppy,puppies,doggo,hound,doberman,pug,poodle,bulldog,labrador,husky,corgi,shiba | chien,chiens,chiot,chiots,toutou | hund,hunde,welpe,welpen | perro,perros,cachorro,perrito | cane,cani,cucciolo | cachorro,cao,caes | 犬,いぬ,イヌ,子犬 | 狗,犬,小狗
cow | animal | cow,cows,cattle,calf,bull,ox,oxen | vache,vaches,veau,taureau,boeuf | kuh,kuhe,rind,rinder,kalb,stier | vaca,vacas,toro,ternero | mucca,mucche,vacca,toro,vitello | vaca,vacas,touro | 牛,うし,ウシ | 牛,奶牛
horse | animal | horse,horses,pony,ponies,stallion,mare | cheval,chevaux,poney,jument | pferd,pferde,pony,stute | caballo,caballos,yegua | cavallo,cavalli,pony | cavalo,cavalos | 馬,うま | 马,馬
pig | animal | pig,pigs,piglet,hog,boar | cochon,cochons,porc,sanglier | schwein,schweine,ferkel | cerdo,cerdos,cochino | maiale,maiali | porco,porcos | 豚,ぶた | 猪
sheep | animal | sheep,lamb,lambs,ram | mouton,moutons,agneau,brebis | schaf,schafe,lamm | oveja,ovejas,cordero | pecora,pecore,agnello | ovelha,cordeiro | 羊,ひつじ | 羊
goat | animal | goat,goats,ibex | chevre,chevres,bouquetin | ziege,ziegen,steinbock | cabra,cabras | capra,capre,stambecco | cabra,bode | 山羊,ヤギ | 山羊
rabbit | animal | rabbit,rabbits,bunny,bunnies,hare | lapin,lapins,lievre | hase,hasen,kaninchen | conejo,conejos,liebre | coniglio,conigli,lepre | coelho,coelhos | うさぎ,ウサギ,兎 | 兔子,兔
mouse | animal | mouse,mice,rat,rats,hamster | souris,rat,rats,hamster | maus,mause,ratte,hamster | raton,ratones,rata | topo,topi,ratto,criceto | rato,ratos | ねずみ,ネズミ | 老鼠,鼠
bear | animal | bear,bears,teddy bear,panda | ours,ourson,panda | bar,baren,teddy,panda | oso,osos,panda | orso,orsi,panda | urso,ursos,panda | 熊,クマ,パンダ | 熊,熊猫
wolf | animal | wolf,wolves | loup,loups | wolf,wolfe | lobo,lobos | lupo,lupi | lobo,lobos | 狼,オオカミ | 狼
fox | animal | fox,foxes | renard,renards | fuchs,fuchse | zorro,zorros | volpe,volpi | raposa | 狐,キツネ | 狐狸
tiger | big cat,animal | tiger,tigers,tigress | tigre,tigres,tigresse | tiger,tigerin | tigre,tigres | tigre,tigri | tigre,tigres | 虎,トラ | 老虎,虎
lion | big cat,animal | lion,lions,lioness,merlion | lion,lions,lionne | lowe,lowen,lowin | leon,leones,leona | leone,leoni,leonessa | leao,leoes | ライオン,獅子 | 狮子
big cat | animal | big cat,big cats,leopard,jaguar,panther,cheetah,lynx | felin,felins,leopard,jaguar,panthere,guepard,lynx | raubkatze,leopard,jaguar,panther,gepard,luchs | felino,felinos,leopardo,jaguar,pantera,guepardo,lince | felino,felini,leopardo,giaguaro,pantera,ghepardo,lince | felino,leopardo,onca,pantera | ヒョウ,ジャガー | 豹,猎豹
monkey | animal | monkey,monkeys,ape,apes,gorilla,chimpanzee | singe,singes,gorille,chimpanze | affe,affen,gorilla,schimpanse | mono,monos,gorila,chimpance | scimmia,scimmie,gorilla,scimpanze | macaco,macacos,gorila | 猿,サル,ゴリラ | 猴子,猩猩
elephant | animal | elephant,elephants | elephant,elephants | elefant,elefanten | elefante,elefantes | elefante,elefanti | elefante | 象,ゾウ | 大象,象
giraffe | animal | giraffe,giraffes | girafe,girafes | giraffe,giraffen | jirafa,jirafas | giraffa,giraffe | girafa | キリン | 长颈鹿
deer | animal | deer,stag,reindeer,elk,moose,fawn | cerf,biche,renne,elan,faon | hirsch,reh,rentier,elch | ciervo,venado,reno,alce | cervo,renna,alce | cervo,veado,rena | 鹿,シカ,トナカイ | 鹿
bird | animal | bird,birds,birdie,songbird,sparrow,robin,crow,raven,quail,finch | oiseau,oiseaux,moineau,corbeau,merle,caille | vogel,vogel,spatz,krahe,rabe,wachtel,amsel | pajaro,pajaros,ave,aves,gorrion,cuervo,codorniz | uccello,uccelli,passero,corvo,quaglia | passaro,passaros,ave,aves | 鳥,とり,小鳥 | 鸟,鳥
pigeon | bird,animal | pigeon,pigeons,dove,doves | pigeon,pigeons,colombe | taube,tauben | paloma,palomas | piccione,piccioni,colomba | pombo,pombos,pomba | 鳩,ハト | 鸽子
swan | bird,animal | swan,swans | cygne,cygnes | schwan,schwane | cisne,cisnes | cigno,cigni | cisne | 白鳥,ハクチョウ | 天鹅
duck | bird,animal | duck,ducks,duckling,goose,geese | canard,canards,oie,oies | ente,enten,gans,ganse | pato,patos,ganso | anatra,anatre,oca | pato,patos,ganso | 鴨,アヒル,ガチョウ | 鸭,鹅
chicken | bird,animal | chicken,chickens,hen,hens,rooster,chick,chicks | poule,poules,poulet,coq,poussin | huhn,huhner,henne,hahn,kuken | gallina,gallinas,pollo,gallo,pollito | gallina,galline,pollo,gallo,pulcino | galinha,galinhas,frango,galo | 鶏,にわとり,ニワトリ,ひよこ | 鸡,母鸡,公鸡
parrot | bird,animal | parrot,parrots,macaw,parakeet | perroquet,perroquets,perruche | papagei,papageien,sittich | loro,loros,guacamayo,perico | pappagallo,pappagalli | papagaio,papagaios | オウム,インコ | 鹦鹉
owl | bird,animal | owl,owls | hibou,hiboux,chouette | eule,eulen,uhu | buho,lechuza | gufo,civetta | coruja | フクロウ | 猫头鹰
eagle | bird,animal | eagle,eagles,hawk,falcon | aigle,aigles,faucon | adler,falke,habicht | aguila,halcon | aquila,falco | aguia,falcao | 鷲,タカ | 鹰
penguin | bird,animal | penguin,penguins | pingouin,manchot | pinguin,pinguine | pinguino | pinguino | pinguim | ペンギン | 企鹅
fish | animal | fish,fishes,clownfish,goldfish,koi,salmon,tuna | poisson,poissons,poisson-clown,poisson rouge,saumon,thon | fisch,fische,clownfisch,goldfisch,lachs,thunfisch | pez,peces,pez payaso,salmon,atun | pesce,pesci,pesce pagliaccio,salmone,tonno | peixe,peixes,salmao,atum | 魚,さかな,金魚 | 鱼,魚,金鱼
shark | animal | shark,sharks | requin,requins | hai,haie,haifisch | tiburon,tiburones | squalo,squali | tubarao | サメ | 鲨鱼
whale | animal | whale,whales,orca | baleine,baleines,orque | wal,wale,orca | ballena,ballenas,orca | balena,balene,orca | baleia,orca | クジラ | 鲸
dolphin | animal | dolphin,dolphins | dauphin,dauphins | delfin,delfine | delfin,delfines | delfino,delfini | golfinho | イルカ | 海豚
octopus | animal | octopus,squid,kraken | pieuvre,poulpe,calamar | krake,tintenfisch,oktopus | pulpo,calamar | polpo,calamaro | polvo,lula | タコ,イカ | 章鱼
jellyfish | animal | jellyfish | meduse,meduses | qualle,quallen | medusa,medusas | medusa,meduse | agua-viva | クラゲ | 水母
turtle | animal | turtle,turtles,tortoise | tortue,tortues | schildkrote,schildkroten | tortuga,tortugas | tartaruga,tartarughe | tartaruga | 亀,カメ | 龟,乌龟
frog | animal | frog,frogs,toad | grenouille,grenouilles,crapaud | frosch,frosche,krote | rana,ranas,sapo | rana,rane,rospo | sapo,ra | カエル | 青蛙
snake | animal | snake,snakes,serpent,python,cobra | serpent,serpents | schlange,schlangen | serpiente,serpientes,culebra | serpente,serpenti | cobra,serpente | 蛇,ヘビ | 蛇
lizard | animal | lizard,lizards,reptile,reptiles,reptilian,reptoid,gecko,iguana,chameleon | lezard,lezards,reptile,reptiles,cameleon | eidechse,eidechsen,reptil,reptilien,echse,chamaleon | lagarto,lagartos,reptil,reptiles,camaleon | lucertola,lucertole,rettile,rettili,camaleonte | lagarto,reptil | トカゲ,爬虫類 | 蜥蜴,爬行动物
dragon | creature | dragon,dragons,wyvern,drake,drakes | dragon,dragons,wyverne | drache,drachen,lindwurm | dragon,dragones | drago,draghi | dragao,dragoes | ドラゴン,竜,龍 | 龙,龍
dinosaur | animal | dinosaur,dinosaurs,t-rex,dino,raptor | dinosaure,dinosaures | dinosaurier,dino | dinosaurio,dinosaurios | dinosauro,dinosauri | dinossauro | 恐竜 | 恐龙
unicorn | creature | unicorn,unicorns | licorne,licornes | einhorn,einhorner | unicornio | unicorno | unicornio | ユニコーン | 独角兽
butterfly | insect,animal | butterfly,butterflies,moth,moths | papillon,papillons,mite | schmetterling,schmetterlinge,falter,motte | mariposa,mariposas,polilla | farfalla,farfalle,falena | borboleta,borboletas,mariposa | 蝶,ちょう,チョウ | 蝴蝶
insect | animal | insect,insects,bug,bugs,bee,bees,ant,ants,beetle,ladybug,spider,spiders,dragonfly | insecte,insectes,abeille,fourmi,coccinelle,araignee,libellule | insekt,insekten,biene,ameise,kafer,marienkafer,spinne,libelle | insecto,insectos,abeja,hormiga,mariquita,arana,libelula | insetto,insetti,ape,formica,coccinella,ragno,libellula | inseto,insetos,abelha,formiga,aranha | 虫,昆虫,蜂,クモ | 昆虫,蜜蜂,蜘蛛
creature | | creature,monster,monsters,beast,mascot | creature,monstre,monstres,mascotte | kreatur,monster,ungeheuer,maskottchen | criatura,monstruo,mascota | creatura,mostro,mostri,mascotte | criatura,monstro,mascote | 怪物,モンスター | 怪物,怪兽
person |  | person,people,human,humans,someone | personne,personnes,gens,humain | person,personen,mensch,menschen,leute | persona,personas,gente,humano | persona,persone,gente,umano | pessoa,pessoas,gente | 人,人物 | 人,人物
woman | person | woman,women,lady,ladies,girl,girls,female,wife,mother,mom | femme,femmes,dame,fille,filles,meuf,mere,maman | frau,frauen,dame,madchen,mutter,mama | mujer,mujeres,senora,chica,chicas,nina,madre,mama | donna,donne,signora,ragazza,ragazze,madre,mamma | mulher,mulheres,senhora,menina,moca,mae | 女性,女の子,女,少女 | 女人,女孩,女性
man | person | man,men,guy,guys,boy,boys,male,gentleman,father,dad,dude | homme,hommes,garcon,garcons,mec,monsieur,pere,papa | mann,manner,junge,jungen,herr,kerl,vater,papa | hombre,hombres,chico,chicos,senor,padre,papa | uomo,uomini,ragazzo,ragazzi,signore,padre,papa | homem,homens,rapaz,menino,senhor,pai | 男性,男の子,男,少年 | 男人,男孩,男性
child | person | child,children,kid,kids,baby,babies,toddler,little girl,little boy | enfant,enfants,bebe,bebes,gamin | kind,kinder,baby,kleinkind | nino,ninos,bebe,bebes,hijo | bambino,bambini,bimbo,neonato | crianca,criancas,bebe | 子供,赤ちゃん,こども | 孩子,儿童,婴儿
elderly | person | old woman,old man,elderly,grandmother,grandfather,granny,grandma,grandpa,great-grandmother,senior,old lady | grand-mere,grand-pere,mamie,papy,vieille femme,vieil homme,personne agee | grossmutter,grossvater,oma,opa,alte frau,alter mann,senior | abuela,abuelo,anciana,anciano,abuelita | nonna,nonno,anziana,anziano | avo,avó,idosa,idoso | おばあさん,おじいさん,祖母,祖父 | 奶奶,爷爷,老人
family | person | family,parents,couple,lovers,friends,siblings,mother and child | famille,parents,couple,amis,amoureux | familie,eltern,paar,freunde,geschwister | familia,padres,pareja,amigos | famiglia,genitori,coppia,amici | familia,pais,casal,amigos | 家族,カップル | 家庭,情侣
portrait | style | portrait,portraits,headshot,close-up,closeup,bust,face,faces | portrait,portraits,visage,visages,gros plan | portrat,portrats,gesicht,gesichter,nahaufnahme | retrato,retratos,cara,rostro | ritratto,ritratti,volto,viso,primo piano | retrato,retratos,rosto | 肖像,顔,ポートレート | 肖像,脸,人像
selfie | portrait | selfie,selfies,self-portrait,self portrait,myself | selfie,autoportrait | selfie,selbstportrat | selfie,autorretrato | selfie,autoritratto | selfie,autorretrato | 自撮り,セルフィー | 自拍,自画像
mirror selfie | selfie | mirror selfie,mirror selfies,selfie in a mirror,selfie in the mirror,mirror | selfie miroir,selfie dans le miroir,miroir | spiegelselfie,spiegel-selfie,spiegel | selfie en el espejo,espejo | selfie allo specchio,specchio | selfie no espelho,espelho | 鏡,ミラー | 镜子
eyes | face | eyes,eye,green eyes,blue eyes,gaze,stare,greeneyes,blueeyes | yeux,oeil,regard,yeux verts,yeux bleus | augen,auge,blick,grune augen | ojos,ojo,mirada,ojos verdes | occhi,occhio,sguardo,occhi verdi | olhos,olho,olhar | 目,瞳 | 眼睛
face | person | face,faces,smile,smiling,grin,laugh,laughing | visage,sourire,souriant,souriante,rire | gesicht,lacheln,lachelnd,lachen | cara,sonrisa,sonriendo,risa | viso,sorriso,sorridente,risata | rosto,sorriso,sorrindo | 顔,笑顔 | 脸,笑容,微笑
hair | person | hair,haircut,braid,braids,blonde,blond,brunette,redhead,ponytail,curly hair,long hair | cheveux,coiffure,tresse,tresses,blonde,brune,rousse,queue de cheval | haare,frisur,zopf,zopfe,blond,brunett,rothaarig | pelo,cabello,peinado,trenza,trenzas,rubia,morena,pelirroja | capelli,acconciatura,treccia,trecce,bionda,bruna,rossa | cabelo,penteado,tranca,loira,morena,ruiva | 髪,金髪 | 头发,金发
beard | man | beard,bearded,mustache,moustache,goatee,stubble | barbe,barbu,moustache | bart,bartig,schnurrbart | barba,barbudo,bigote | barba,barbuto,baffi | barba,barbudo,bigode | ひげ,髭 | 胡子
glasses | accessory | glasses,eyeglasses,spectacles,goggles | lunettes | brille,brillen | gafas,anteojos,lentes | occhiali | oculos | 眼鏡,メガネ | 眼镜
sunglasses | glasses,accessory | sunglasses,shades,visor | lunettes de soleil | sonnenbrille | gafas de sol | occhiali da sole | oculos de sol | サングラス | 太阳镜,墨镜
hat | accessory | hat,hats,cap,caps,baseball cap,beanie,straw hat,cowboy hat,party hat,helmet,crown,headband,bandana | chapeau,chapeaux,casquette,bonnet,casque,couronne,bandeau | hut,hute,mutze,kappe,helm,krone,stirnband | sombrero,gorra,gorro,casco,corona | cappello,berretto,cuffia,casco,corona | chapeu,bone,gorro,capacete,coroa | 帽子,キャップ,ヘルメット | 帽子,头盔
mask | accessory | mask,masks,gas mask,balaclava,masked,guy fawkes,fawkes | masque,masques,masque a gaz,cagoule,masque de fawkes | maske,masken,gasmaske,sturmhaube | mascara,mascaras,mascara de gas,pasamontanas | maschera,maschere,maschera antigas,passamontagna | mascara,mascaras,balaclava | マスク,仮面,ガスマスク | 面具,口罩,防毒面具
tattoo | person | tattoo,tattoos,tattooed,ink | tatouage,tatouages,tatoue | tattoo,tattoos,tatowierung,tatowiert | tatuaje,tatuajes,tatuado | tatuaggio,tatuaggi,tatuato | tatuagem,tatuagens | タトゥー,刺青 | 纹身
shirtless | man | shirtless,topless,bare chest,bare-chested,muscles,abs,six pack | torse nu,musclé,abdos | oben ohne,nackter oberkorper,muskeln | sin camisa,torso desnudo,musculos | a torso nudo,muscoli,addominali | sem camisa,musculos | 上半身裸 | 赤膊,肌肉
knight | character | knight,knights,armor,armour,paladin,warrior,warriors,soldier,soldiers,gladiator | chevalier,chevaliers,armure,guerrier,guerriers,soldat,soldats | ritter,rustung,krieger,soldat,soldaten | caballero,caballeros,armadura,guerrero,guerreros,soldado | cavaliere,cavalieri,armatura,guerriero,soldato | cavaleiro,armadura,guerreiro,soldado | 騎士,戦士,兵士 | 骑士,战士,士兵
samurai | character | samurai,ninja,ninjas,katana,ronin | samourai,ninja | samurai,ninja | samurai,ninja | samurai,ninja | samurai,ninja | 侍,忍者 | 武士,忍者
pirate | character | pirate,pirates,buccaneer,captain hook | pirate,pirates,corsaire | pirat,piraten,seerauber | pirata,piratas,corsario | pirata,pirati,corsaro | pirata,piratas | 海賊 | 海盗
astronaut | character | astronaut,astronauts,cosmonaut,spaceman,space suit,spacesuit,nasa | astronaute,astronautes,cosmonaute,combinaison spatiale | astronaut,astronauten,raumfahrer,raumanzug | astronauta,astronautas,cosmonauta,traje espacial | astronauta,astronauti,tuta spaziale | astronauta,astronautas | 宇宙飛行士 | 宇航员
diver | character | diver,divers,scuba,diving,snorkel,diving helmet,flippers | plongeur,plongeuse,plongee,scaphandre | taucher,taucherin,tauchen,taucherhelm | buzo,buceador,buceo | sub,subacqueo,immersione,palombaro | mergulhador,mergulho | ダイバー,潜水 | 潜水员,潜水
superhero | character | superhero,superheroes,super hero,hero,cape,batman,superman,spiderman,spider-man,wonder woman,teen titans,starfire | superheros,super-heros,heros,cape | superheld,superhelden,held,umhang | superheroe,superheroes,heroe,capa | supereroe,supereroi,eroe,mantello | super-heroi,heroi,capa | スーパーヒーロー,ヒーロー | 超级英雄,英雄
robot | character | robot,robots,android,cyborg,mech,terminator,droid | robot,robots,androide,cyborg | roboter,android,cyborg | robot,robots,androide,ciborg | robot,androide,cyborg | robo,robos,androide,ciborgue | ロボット,アンドロイド | 机器人
alien | character | alien,aliens,extraterrestrial,martian,ufo,ufos,flying saucer,space invader,space invaders | extraterrestre,alien,martien,ovni,soucoupe volante | ausserirdischer,alien,ufo,marsmensch,fliegende untertasse | extraterrestre,alienigena,ovni,platillo volante | alieno,extraterrestre,ufo,disco volante | alienigena,extraterrestre,ovni,disco voador | 宇宙人,エイリアン,UFO | 外星人,飞碟
princess | character | princess,princesses,queen,queens,peach,princess peach,empress | princesse,princesses,reine,reines | prinzessin,konigin | princesa,princesas,reina | principessa,regina | princesa,rainha | 王女,姫,女王 | 公主,女王
king | character | king,kings,emperor,pharaoh,prince,royal | roi,rois,empereur,pharaon,prince | konig,kaiser,pharao,prinz | rey,reyes,emperador,faraon,principe | re,imperatore,faraone,principe | rei,imperador,farao,principe | 王,皇帝,ファラオ | 国王,皇帝,法老
egypt | place | egypt,egyptian,pharaoh,pyramid,pyramids,sphinx,horus,hieroglyphs | egypte,egyptien,egyptienne,pyramide,sphinx,hieroglyphes | agypten,agyptisch,pyramide,sphinx,hieroglyphen | egipto,egipcio,piramide,esfinge | egitto,egiziano,piramide,sfinge | egito,egipcio,piramide | エジプト,ピラミッド | 埃及,金字塔
angel | character | angel,angels,wings,halo | ange,anges,ailes,aureole | engel,flugel,heiligenschein | angel,angeles,alas | angelo,angeli,ali | anjo,anjos,asas | 天使 | 天使
demon | character | demon,demons,devil,devils,satan,satanic,hell,hellish | demon,demons,diable,satan,satanique,enfer | damon,teufel,satan,satanisch,holle | demonio,diablo,satan,satanico,infierno | demone,diavolo,satana,satanico,inferno | demonio,diabo,inferno | 悪魔,地獄 | 恶魔,魔鬼,地狱
ghost | character | ghost,ghosts,spirit,phantom,skeleton,skeletons,skull,skulls,zombie,zombies,vampire,witch,wizard,mage | fantome,fantomes,esprit,squelette,crane,zombie,vampire,sorciere,sorcier,mage | geist,gespenst,skelett,schadel,zombie,vampir,hexe,zauberer,magier | fantasma,espiritu,esqueleto,calavera,zombi,vampiro,bruja,mago | fantasma,spirito,scheletro,teschio,zombie,vampiro,strega,mago | fantasma,esqueleto,caveira,zumbi,vampiro,bruxa,mago | 幽霊,骸骨,ゾンビ,魔女,魔法使い | 鬼,骷髅,僵尸,女巫,巫师
clown | character | clown,clowns,jester,joker | clown,clowns,bouffon | clown,clowns,narr | payaso,payasos,bufon | pagliaccio,giullare | palhaco | ピエロ | 小丑
video game | style | video game,video games,videogame,game,gaming,gamer,arcade,8-bit,16-bit,sprite,sprites,retro game,console,controller,gameboy,nintendo,playstation,gta,gta6 | jeu video,jeux video,jeu,arcade,manette,console | videospiel,videospiele,spiel,spiele,arcade,konsole,controller | videojuego,videojuegos,juego,arcade,consola,mando | videogioco,videogiochi,gioco,arcade,console | videogame,jogo,jogos,arcade,console | ゲーム,ビデオゲーム,ドット絵 | 游戏,电子游戏,像素
video game character | character,video game | mario,luigi,waluigi,wario,peach,bowser,yoshi,toad,zelda,link,sonic,pikachu,pokemon,kirby,pac-man,pacman,donkey kong,megaman,mega man,street fighter,ryu,chun-li,mario kart,minecraft,steve | mario,sonic,pikachu,pokemon,zelda | mario,sonic,pikachu,pokemon,zelda | mario,sonic,pikachu,pokemon,zelda | mario,sonic,pikachu,pokemon,zelda | mario,sonic,pikachu,pokemon,zelda | マリオ,ソニック,ピカチュウ,ポケモン,ゼルダ | 马里奥,索尼克,皮卡丘,宝可梦
cartoon | style | cartoon,cartoons,cartoon character,animated,animation,anime,manga,comic,comics,simpsons,homer,homer simpson,bart simpson,spongebob,sponge-bob,patrick,patrick star,hello kitty,mickey,disney,looney tunes,teen titans | dessin anime,dessins animes,bande dessinee,bd,anime,manga | zeichentrick,cartoon,comic,comics,anime,manga | dibujos animados,caricatura,historieta,comic,anime,manga | cartone animato,cartoni,fumetto,fumetti,anime,manga | desenho animado,quadrinhos,anime,manga | アニメ,漫画,マンガ,キャラクター | 卡通,动画,漫画
meme | style | meme,memes,funny,joke,lol,humor,humour | meme,memes,drole,blague,humour | meme,memes,lustig,witz,humor | meme,memes,gracioso,chiste,humor | meme,divertente,battuta,umorismo | meme,engracado,piada,humor | ミーム,面白い | 表情包,搞笑
city | place | city,cities,town,towns,cityscape,skyline,downtown,metropolis,urban,village,villages | ville,villes,village,cite,metropole,urbain | stadt,stadte,dorf,dorfer,skyline,grossstadt | ciudad,ciudades,pueblo,aldea,urbano | citta,paese,villaggio,borgo,urbano | cidade,cidades,vila,aldeia,urbano | 都市,町,街,村 | 城市,城镇,村庄
street | city | street,streets,road,roads,avenue,alley,boulevard,highway,sidewalk,crossing | rue,rues,route,routes,avenue,ruelle,boulevard,autoroute,trottoir | strasse,strassen,weg,allee,gasse,autobahn | calle,calles,carretera,avenida,callejon | strada,strade,via,viale,vicolo,autostrada | rua,ruas,estrada,avenida,beco | 道,通り,道路 | 街道,马路,道路
building | city | building,buildings,architecture,house,houses,hotel,palace,mansion,skyscraper,tower,towers,facade | batiment,batiments,immeuble,maison,maisons,hotel,palais,manoir,gratte-ciel,tour,tours | gebaude,haus,hauser,hotel,palast,villa,wolkenkratzer,turm | edificio,edificios,casa,casas,hotel,palacio,mansion,rascacielos,torre | edificio,edifici,casa,case,albergo,palazzo,villa,grattacielo,torre | edificio,predio,casa,casas,hotel,palacio,arranha-ceu,torre | 建物,家,ホテル,宮殿,塔 | 建筑,房子,酒店,宫殿,塔
castle | building | castle,castles,fortress,citadel,fort | chateau,chateaux,forteresse,citadelle,fort | burg,burgen,schloss,festung | castillo,castillos,fortaleza,ciudadela | castello,castelli,fortezza,rocca | castelo,castelos,fortaleza | 城 | 城堡
church | building | church,churches,cathedral,chapel,temple,temples,mosque,pagoda,shrine,monastery | eglise,eglises,cathedrale,chapelle,temple,mosquee,pagode,sanctuaire | kirche,kirchen,dom,kathedrale,kapelle,tempel,moschee,pagode | iglesia,iglesias,catedral,capilla,templo,mezquita,pagoda | chiesa,chiese,cattedrale,cappella,tempio,moschea,pagoda | igreja,igrejas,catedral,capela,templo,mesquita,pagode | 教会,寺,神社,塔,大聖堂 | 教堂,寺庙,宝塔,大教堂
monument | building | monument,monuments,landmark,taj mahal,eiffel tower,statue,statues,capitol,colosseum | monument,monuments,tour eiffel,statue,statues | denkmal,wahrzeichen,eiffelturm,statue | monumento,monumentos,torre eiffel,estatua | monumento,monumenti,torre eiffel,statua | monumento,monumentos,torre eiffel,estatua | 記念碑,タージ・マハル,エッフェル塔,像 | 纪念碑,泰姬陵,埃菲尔铁塔,雕像
bridge | city | bridge,bridges,viaduct,aqueduct | pont,ponts,viaduc,aqueduc | brucke,brucken,viadukt | puente,puentes,viaducto | ponte,ponti,viadotto | ponte,pontes,viaduto | 橋 | 桥
station | city | station,train station,railway station,platform,railway,railroad,rails,tracks,subway,metro | gare,quai,voie ferree,rails,metro | bahnhof,bahnsteig,gleis,gleise,schienen,u-bahn | estacion,anden,via ferrea,rieles,metro | stazione,binario,binari,ferrovia,metropolitana | estacao,plataforma,trilhos,metro | 駅,ホーム,線路 | 车站,站台,铁轨,地铁
room | place | room,rooms,interior,bedroom,living room,kitchen,office,studio,desk,fireplace,cozy room,bathroom | chambre,piece,salon,cuisine,bureau,interieur,cheminee | zimmer,raum,schlafzimmer,wohnzimmer,kuche,buro,schreibtisch,kamin | habitacion,cuarto,salon,cocina,oficina,escritorio,chimenea | stanza,camera,soggiorno,cucina,ufficio,scrivania,camino | quarto,sala,cozinha,escritorio,lareira | 部屋,室内,キッチン | 房间,室内,厨房,办公室
museum | building | museum,museums,gallery,exhibition | musee,musees,galerie,exposition | museum,museen,galerie,ausstellung | museo,museos,galeria,exposicion | museo,musei,galleria,mostra | museu,galeria,exposicao | 美術館,博物館,絵画 | 博物馆,美术馆,画
mountain | nature | mountain,mountains,mount,alps,alpine,peak,peaks,summit,hill,hills,volcano,cliff,cliffs,valley,valleys,mount fuji,fuji | montagne,montagnes,mont,alpes,alpin,sommet,colline,collines,volcan,falaise,vallee,col | berg,berge,gebirge,alpen,gipfel,hugel,vulkan,klippe,tal,taler | montana,montanas,monte,alpes,cumbre,colina,volcan,acantilado,valle | montagna,montagne,monte,alpi,vetta,collina,vulcano,scogliera,valle | montanha,montanhas,monte,alpes,pico,colina,vulcao,penhasco,vale | 山,山脈,富士山,ふじさん,富士,火山,谷 | 山,山脉,富士山,火山,山谷
lake | water | lake,lakes,pond,lagoon,reservoir,loch,lakeside | lac,lacs,etang,lagune | see,seen,teich,weiher,lagune | lago,lagos,estanque,laguna | lago,laghi,stagno,laguna | lago,lagos,lagoa | 湖,池 | 湖,池塘
river | water | river,rivers,stream,creek,canal,waterfall,waterfalls,fountain | riviere,fleuve,ruisseau,canal,cascade,chute,fontaine | fluss,flusse,bach,kanal,wasserfall,brunnen | rio,rios,arroyo,canal,cascada,fuente | fiume,fiumi,torrente,canale,cascata,fontana | rio,rios,riacho,canal,cachoeira,fonte | 川,河,滝,噴水 | 河,河流,瀑布,喷泉
sea | water | sea,seas,ocean,oceans,waves,wave,coast,coastline,shore,bay,harbor,harbour,port,marina,seaside | mer,mers,ocean,vague,vagues,cote,rivage,baie,port | meer,meere,ozean,welle,wellen,kuste,ufer,bucht,hafen | mar,mares,oceano,ola,olas,costa,orilla,bahia,puerto | mare,mari,oceano,onda,onde,costa,riva,baia,porto | mar,oceano,onda,ondas,costa,baia,porto | 海,波,海岸,港 | 海,海洋,波浪,海岸,港口
beach | sea | beach,beaches,sand,sandy,shore,palm,palms,palm tree,palm trees,tropical | plage,plages,sable,palmier,palmiers,tropical | strand,strande,sand,palme,palmen,tropisch | playa,playas,arena,palmera,palmeras,tropical | spiaggia,spiagge,sabbia,palma,palme,tropicale | praia,praias,areia,palmeira,palmeiras | ビーチ,浜辺,砂浜,ヤシ | 海滩,沙滩,棕榈
underwater | water | underwater,under water,undersea,coral,reef,deep sea,aquarium,seabed | sous l'eau,sous-marin,corail,recif,fond marin,aquarium | unterwasser,unter wasser,koralle,riff,tiefsee,aquarium | bajo el agua,submarino,coral,arrecife,acuario | sott'acqua,subacqueo,corallo,barriera,acquario | subaquatico,coral,recife,aquario | 水中,海中,サンゴ | 水下,海底,珊瑚
water | nature | water,swim,swimming,pool,swimming pool,bath | eau,nager,natation,piscine,baignade | wasser,schwimmen,schwimmbad,pool,baden | agua,nadar,natacion,piscina | acqua,nuotare,nuoto,piscina | agua,nadar,natacao,piscina | 水,泳ぐ,プール | 水,游泳,泳池
desert | nature | desert,deserts,dunes,dune,sand dunes,arid,cactus,oasis | desert,deserts,dune,dunes,cactus,oasis | wuste,wusten,dune,dunen,kaktus,oase | desierto,desiertos,duna,dunas,cactus,oasis | deserto,deserti,duna,dune,cactus,oasi | deserto,desertos,duna,dunas,cacto,oasis | 砂漠,サボテン | 沙漠,仙人掌
forest | nature | forest,forests,woods,wood,woodland,jungle,rainforest,bamboo,bamboo forest,trees | foret,forets,bois,jungle,bambou,bambous,arbres | wald,walder,dschungel,bambus,baume | bosque,bosques,selva,jungla,bambu,arboles | foresta,foreste,bosco,giungla,bambu,alberi | floresta,florestas,bosque,selva,bambu,arvores | 森,森林,竹,竹林,ジャングル | 森林,树林,竹林,丛林
tree | plant | tree,trees,maple,oak,pine,palm tree,cherry tree,birch,willow | arbre,arbres,erable,chene,pin,cerisier,bouleau,saule | baum,baume,ahorn,eiche,kiefer,tanne,kirschbaum,birke,weide | arbol,arboles,arce,roble,pino,cerezo,abedul,sauce | albero,alberi,acero,quercia,pino,ciliegio,betulla,salice | arvore,arvores,bordo,carvalho,pinheiro,cerejeira | 木,樹,桜の木,松,カエデ | 树,树木,枫树,松树
plant | nature | plant,plants,leaves,leaf,foliage,grass,moss,ivy,vine,cactus,fern | plante,plantes,feuille,feuilles,feuillage,herbe,mousse,lierre | pflanze,pflanzen,blatt,blatter,laub,gras,moos,efeu | planta,plantas,hoja,hojas,follaje,hierba,cesped,musgo | pianta,piante,foglia,foglie,fogliame,erba,muschio,edera | planta,plantas,folha,folhas,grama,musgo | 植物,葉,草 | 植物,叶子,草
flower | plant | flower,flowers,floral,blossom,blossoms,bloom,bouquet,petals,daisy,tulip,lily,orchid,snowdrop,galanthus,lotus,lavender | fleur,fleurs,floral,bouquet,petales,marguerite,tulipe,lys,orchidee,perce-neige,lotus,lavande | blume,blumen,blute,bluten,strauss,blutenblatter,ganseblumchen,tulpe,lilie,orchidee,schneeglockchen,lavendel | flor,flores,floral,ramo,petalos,margarita,tulipan,lirio,orquidea,loto,lavanda | fiore,fiori,floreale,mazzo,petali,margherita,tulipano,giglio,orchidea,bucaneve,loto,lavanda | flor,flores,floral,buque,petalas,margarida,tulipa,lirio,orquidea,lotus,lavanda | 花,花束,チューリップ | 花,花朵,花束,郁金香
rose | flower | rose,roses | rose,roses | rose,rosen | rosa,rosas | rosa,rose | rosa,rosas | バラ,薔薇 | 玫瑰
sunflower | flower | sunflower,sunflowers | tournesol,tournesols | sonnenblume,sonnenblumen | girasol,girasoles | girasole,girasoli | girassol,girassois | ひまわり,向日葵 | 向日葵
cherry blossom | flower,tree | cherry blossom,cherry blossoms,sakura,cherry tree,blossoming tree | fleur de cerisier,fleurs de cerisier,sakura,cerisier en fleurs | kirschblute,kirschbluten,sakura | flor de cerezo,flores de cerezo,sakura | fiori di ciliegio,fiore di ciliegio,sakura | flor de cerejeira,sakura | 桜,さくら,サクラ | 樱花
mushroom | plant | mushroom,mushrooms,fungus,fungi,toadstool,fly agaric,amanita | champignon,champignons,amanite | pilz,pilze,fliegenpilz | seta,setas,hongo,hongos,champinon,amanita | fungo,funghi,amanita | cogumelo,cogumelos,fungo | キノコ,きのこ | 蘑菇
field | nature | field,fields,meadow,meadows,farm,farmland,countryside,pasture,wheat,crop,crops,rice field,prairie,grassland | champ,champs,prairie,prairies,ferme,campagne,pature,ble,riziere | feld,felder,wiese,wiesen,bauernhof,land,weide,weizen,reisfeld | campo,campos,prado,granja,campina,pasto,trigo,arrozal | campo,campi,prato,fattoria,campagna,pascolo,grano,risaia | campo,campos,prado,fazenda,pasto,trigo | 畑,田んぼ,牧場,草原 | 田野,农场,草地,麦田
garden | nature | garden,gardens,park,parks,lawn | jardin,jardins,parc,parcs,pelouse | garten,garten,park,parks,rasen | jardin,jardines,parque,parques,cesped | giardino,giardini,parco,parchi,prato | jardim,jardins,parque,parques | 庭,公園 | 花园,公园
landscape | style | landscape,landscapes,scenery,view,vista,panorama,nature,outdoors,countryside | paysage,paysages,vue,panorama,nature | landschaft,landschaften,aussicht,panorama,natur | paisaje,paisajes,vista,panorama,naturaleza | paesaggio,paesaggi,vista,panorama,natura | paisagem,paisagens,vista,panorama,natureza | 風景,景色,自然 | 风景,景色,自然
sky | nature | sky,skies,clouds,cloud,cloudy,blue sky,horizon | ciel,cieux,nuage,nuages,nuageux,horizon | himmel,wolke,wolken,bewolkt,horizont | cielo,cielos,nube,nubes,horizonte | cielo,nuvola,nuvole,orizzonte | ceu,nuvem,nuvens,horizonte | 空,雲 | 天空,云
sunset | sky | sunset,sunsets,sunrise,dusk,dawn,twilight,golden hour,evening sky | coucher de soleil,couchers de soleil,lever de soleil,crepuscule,aube | sonnenuntergang,sonnenaufgang,dammerung,abendrot | puesta de sol,atardecer,amanecer,crepusculo | tramonto,tramonti,alba,crepuscolo | por do sol,nascer do sol,crepusculo | 夕日,夕焼け,日の出 | 日落,夕阳,日出
night | sky | night,nighttime,night sky,midnight,moonlight,stars,starry,neon,neon lights | nuit,nocturne,ciel etoile,minuit,etoiles,neon | nacht,nachts,sternenhimmel,mitternacht,sterne,neon | noche,nocturno,medianoche,estrellas,neon | notte,notturno,mezzanotte,stelle,neon | noite,noturno,meia-noite,estrelas,neon | 夜,夜空,星,ネオン | 夜,夜晚,夜空,星星,霓虹
sun | sky | sun,sunny,sunshine,sunlight | soleil,ensoleille | sonne,sonnig,sonnenschein | sol,soleado | sole,soleggiato | sol,ensolarado | 太陽,日差し | 太阳,阳光
moon | space | moon,moons,lunar,full moon,crescent | lune,lunes,lunaire,pleine lune | mond,monde,vollmond | luna,lunas,lunar,luna llena | luna,lune,lunare,luna piena | lua,luas,lunar,lua cheia | 月,満月 | 月亮,月球
space | nature | space,outer space,universe,cosmos,galaxy,planet,planets,earth,mars,stars,nebula,rocket,spaceship,spacecraft,satellite | espace,univers,cosmos,galaxie,planete,planetes,terre,fusee,vaisseau spatial | weltraum,weltall,universum,kosmos,galaxie,planet,planeten,erde,rakete,raumschiff | espacio,universo,cosmos,galaxia,planeta,planetas,tierra,cohete,nave espacial | spazio,universo,cosmo,galassia,pianeta,pianeti,terra,razzo,astronave | espaco,universo,cosmos,galaxia,planeta,planetas,terra,foguete,nave espacial | 宇宙,惑星,地球,ロケット,宇宙船 | 太空,宇宙,星系,行星,地球,火箭,飞船
weather | nature | weather,rain,rainy,storm,thunder,lightning,snow,snowy,fog,foggy,umbrella,rainbow | meteo,pluie,orage,tonnerre,eclair,neige,brouillard,parapluie,arc-en-ciel | wetter,regen,sturm,gewitter,blitz,schnee,nebel,regenschirm,regenbogen | clima,lluvia,tormenta,trueno,rayo,nieve,niebla,paraguas,arcoiris | meteo,pioggia,tempesta,tuono,fulmine,neve,nebbia,ombrello,arcobaleno | tempo,chuva,tempestade,raio,neve,nevoeiro,guarda-chuva,arco-iris | 雨,嵐,雪,虹,傘 | 雨,暴风雨,雪,彩虹,伞
winter | season | winter,snow,snowy,snowman,ice,frozen,frost | hiver,neige,bonhomme de neige,glace,gel | winter,schnee,schneemann,eis,frost | invierno,nieve,muneco de nieve,hielo | inverno,neve,pupazzo di neve,ghiaccio | inverno,neve,boneco de neve,gelo | 冬,雪,雪だるま | 冬天,雪,雪人
autumn | season | autumn,fall leaves,autumn leaves,maple leaves | automne,feuilles mortes | herbst,herbstlaub | otono,hojas de otono | autunno,foglie autunnali | outono,folhas de outono | 秋,紅葉 | 秋天,红叶
summer | season | summer,summertime,vacation,holiday,holidays | ete,vacances | sommer,ferien,urlaub | verano,vacaciones | estate,vacanze | verao,ferias | 夏,夏休み | 夏天,假期
spring | season | spring,springtime | printemps | fruhling | primavera | primavera | primavera | 春 | 春天
travel | | travel,travels,traveling,travelling,trip,journey,tourism,tourist,vacation,holiday,sightseeing | voyage,voyages,voyager,tourisme,touriste,excursion | reise,reisen,ausflug,tourismus,tourist,urlaub | viaje,viajes,viajar,turismo,turista,excursion | viaggio,viaggi,viaggiare,turismo,turista,gita | viagem,viagens,viajar,turismo,turista | 旅行,旅,観光 | 旅行,旅游
car | vehicle | car,cars,automobile,auto,suv,truck,jeep,van,taxi,race car,sports car,kart,go-kart | voiture,voitures,auto,camion,camionnette,taxi,bolide | auto,autos,wagen,lastwagen,lkw,taxi,rennwagen,sportwagen | coche,coches,carro,auto,camion,camioneta,taxi | auto,macchina,automobile,camion,furgone,taxi | carro,carros,automovel,caminhao,taxi | 車,自動車,トラック,タクシー | 汽车,车,卡车,出租车
bicycle | vehicle | bicycle,bicycles,bike,bikes,mountain bike,cycling,cyclist | velo,velos,bicyclette,vtt,cyclisme,cycliste | fahrrad,fahrrader,rad,mountainbike,radfahrer | bicicleta,bicicletas,bici,ciclista | bicicletta,biciclette,bici,ciclista | bicicleta,bicicletas,bike,ciclista | 自転車 | 自行车
motorcycle | vehicle | motorcycle,motorcycles,motorbike,scooter,moped | moto,motos,motocyclette,scooter | motorrad,motorrader,roller | motocicleta,moto,motos,scooter | moto,motocicletta,scooter | moto,motocicleta,lambreta | バイク,オートバイ | 摩托车
train | vehicle | train,trains,railway,locomotive,tram,funicular,cable car,shinkansen,bullet train,subway train | train,trains,locomotive,tramway,funiculaire,telepherique,tgv | zug,zuge,bahn,lokomotive,strassenbahn,standseilbahn,seilbahn | tren,trenes,locomotora,tranvia,funicular,teleferico | treno,treni,locomotiva,tram,funicolare,funivia | trem,trens,locomotiva,bonde,funicular,teleferico | 電車,列車,新幹線,汽車,ケーブルカー | 火车,列车,新干线,高铁,电车
airplane | vehicle | airplane,airplanes,aeroplane,plane,planes,aircraft,jet,jets,fighter jet,f-16,biplane,airliner,helicopter,flying | avion,avions,aeroplane,chasseur,biplan,helicoptere | flugzeug,flugzeuge,flieger,jet,kampfjet,doppeldecker,hubschrauber | avion,aviones,aeroplano,caza,biplano,helicoptero | aereo,aerei,aeroplano,caccia,biplano,elicottero | aviao,avioes,jato,caca,helicoptero | 飛行機,ジェット機,ヘリコプター | 飞机,喷气机,直升机
boat | vehicle | boat,boats,ship,ships,yacht,yachts,sailboat,sailing,ferry,steamboat,canoe,kayak,cruise,vessel | bateau,bateaux,navire,navires,yacht,voilier,ferry,canoe,kayak,croisiere | boot,boote,schiff,schiffe,yacht,segelboot,fahre,kanu,kajak,kreuzfahrt | barco,barcos,buque,yate,velero,ferry,canoa,kayak,crucero | barca,barche,nave,navi,yacht,veliero,traghetto,canoa,kayak,crociera | barco,barcos,navio,iate,veleiro,balsa,canoa,caiaque | 船,ボート,ヨット,フェリー | 船,小船,游艇,帆船,渡轮
rocket | space,vehicle | rocket,rockets,spaceship,spaceships,spacecraft,shuttle,space shuttle | fusee,fusees,vaisseau,navette spatiale | rakete,raketen,raumschiff,raumfahre | cohete,cohetes,nave,transbordador | razzo,razzi,astronave,navetta | foguete,foguetes,nave,onibus espacial | ロケット,宇宙船 | 火箭,飞船
food | | food,foods,meal,meals,dish,dishes,cuisine,lunch,dinner,breakfast,snack,cooking,plate,bowl,eating | nourriture,repas,plat,plats,cuisine,dejeuner,diner,petit-dejeuner,assiette,bol,manger,bouffe | essen,lebensmittel,mahlzeit,gericht,gerichte,kuche,mittagessen,abendessen,fruhstuck,teller,schussel | comida,comidas,plato,platos,cocina,almuerzo,cena,desayuno,cuenco | cibo,pasto,piatto,piatti,cucina,pranzo,cena,colazione,ciotola | comida,refeicao,prato,pratos,cozinha,almoco,jantar,cafe da manha,tigela | 食べ物,料理,食事,ご飯,弁当 | 食物,食品,饭,菜,料理
sushi | food | sushi,maki,nigiri,sashimi,japanese food | sushi,maki,sashimi | sushi,maki,sashimi | sushi,maki,sashimi | sushi,maki,sashimi | sushi,sashimi | 寿司,すし,刺身 | 寿司,生鱼片
korean food | food | kimchi,kimchee,bibimbap,korean food | kimchi,cuisine coreenne | kimchi,koreanisches essen | kimchi,comida coreana | kimchi,cucina coreana | kimchi,comida coreana | キムチ,韓国料理 | 泡菜,韩国菜
meat | food | meat,ham,jamon,jamon iberico,bacon,steak,sausage,sausages,salami,prosciutto,barbecue,bbq | viande,jambon,jamon,bacon,steak,saucisse,saucisson,charcuterie,barbecue | fleisch,schinken,speck,steak,wurst,wurste,salami,grillen | carne,jamon,tocino,filete,salchicha,chorizo,embutido,barbacoa | carne,prosciutto,pancetta,bistecca,salsiccia,salame,grigliata | carne,presunto,bacon,bife,linguica,salame,churrasco | 肉,ハム,ステーキ,ソーセージ | 肉,火腿,牛排,香肠
dessert | food | dessert,desserts,cake,cakes,candy,candies,sweets,cookie,cookies,donut,donuts,chocolate,ice cream,cupcake,pastry,sprinkles,lollipop | dessert,gateau,gateaux,bonbon,bonbons,sucreries,biscuit,beignet,chocolat,glace,patisserie,sucette | nachtisch,dessert,kuchen,torte,bonbon,bonbons,sussigkeiten,keks,kekse,donut,schokolade,eis,gebaeck | postre,postres,pastel,tarta,caramelo,caramelos,dulces,galleta,donut,chocolate,helado | dolce,dolci,torta,caramella,caramelle,biscotto,ciambella,cioccolato,gelato,pasticcino | sobremesa,bolo,doce,doces,bala,biscoito,rosquinha,chocolate,sorvete | ケーキ,お菓子,キャンディ,チョコレート,アイスクリーム | 甜点,蛋糕,糖果,巧克力,冰淇淋
fruit | food | fruit,fruits,apple,apples,banana,bananas,strawberry,strawberries,cherry,cherries,grapes,watermelon,lemon,pineapple | fruit,fruits,pomme,pommes,banane,fraise,fraises,cerise,cerises,raisin,pasteque,citron,ananas | obst,frucht,fruchte,apfel,banane,erdbeere,kirsche,kirschen,trauben,wassermelone,zitrone,ananas | fruta,frutas,manzana,platano,fresa,cereza,uvas,sandia,limon,pina | frutta,frutto,mela,banana,fragola,ciliegia,uva,anguria,limone,ananas | fruta,frutas,maca,banana,morango,cereja,uva,melancia,limao,abacaxi | 果物,りんご,バナナ,いちご | 水果,苹果,香蕉,草莓
pizza | food | pizza,pizzas,burger,burgers,hamburger,fries,hot dog,fast food,sandwich | pizza,burger,hamburger,frites,sandwich,fast-food | pizza,burger,hamburger,pommes,sandwich,fastfood | pizza,hamburguesa,papas fritas,sandwich,comida rapida | pizza,hamburger,patatine,panino,fast food | pizza,hamburguer,batata frita,sanduiche | ピザ,ハンバーガー | 披萨,汉堡
drink | food | drink,drinks,coffee,latte,cappuccino,espresso,tea,wine,beer,cocktail,juice,glass of wine,cup | boisson,boissons,cafe,the,vin,biere,cocktail,jus,tasse,verre | getrank,getranke,kaffee,tee,wein,bier,cocktail,saft,tasse,glas | bebida,bebidas,cafe,te,vino,cerveza,coctel,zumo,jugo,taza | bevanda,bevande,caffe,te,vino,birra,cocktail,succo,tazza | bebida,bebidas,cafe,cha,vinho,cerveja,coquetel,suco,xicara | 飲み物,コーヒー,お茶,ワイン,ビール | 饮料,咖啡,茶,葡萄酒,啤酒
computer | object | computer,computers,laptop,laptops,pc,screen,monitor,keyboard,server,servers,terminal,console,code,coding,programming,hacker | ordinateur,ordinateurs,portable,ecran,clavier,serveur,serveurs,terminal,code,programmation | computer,rechner,laptop,bildschirm,monitor,tastatur,server,terminal,code,programmieren | ordenador,computadora,portatil,pantalla,teclado,servidor,terminal,codigo,programacion | computer,portatile,schermo,tastiera,server,terminale,codice,programmazione | computador,notebook,tela,teclado,servidor,terminal,codigo,programacao | パソコン,コンピューター,画面,サーバー | 电脑,计算机,笔记本,屏幕,服务器
phone | object | phone,phones,smartphone,iphone,mobile,cellphone,camera,photo camera | telephone,portable,smartphone,iphone,appareil photo | telefon,handy,smartphone,iphone,kamera | telefono,movil,celular,smartphone,iphone,camara | telefono,cellulare,smartphone,iphone,fotocamera | telefone,celular,smartphone,iphone,camera | 電話,スマホ,携帯,カメラ | 手机,电话,相机
video call | computer | video call,videocall,zoom call,conference call,webcam,livestream | appel video,visioconference,webcam | videoanruf,videokonferenz,webcam | videollamada,webcam | videochiamata,webcam | videochamada,webcam | ビデオ通話 | 视频通话
music | object | music,musician,guitar,piano,drums,dj,concert,singer,headphones,rave,techno,microphone | musique,musicien,guitare,piano,batterie,concert,chanteur,casque,micro | musik,musiker,gitarre,klavier,schlagzeug,konzert,sanger,kopfhorer,mikrofon | musica,musico,guitarra,piano,bateria,concierto,cantante,auriculares,microfono | musica,musicista,chitarra,pianoforte,batteria,concerto,cantante,cuffie,microfono | musica,musico,guitarra,piano,bateria,show,cantor,fones,microfone | 音楽,ギター,ピアノ,ヘッドホン | 音乐,吉他,钢琴,耳机
weapon | object | weapon,weapons,sword,swords,shield,shields,gun,guns,rifle,bow,arrow,axe,spear,dagger,katana | arme,armes,epee,epees,bouclier,pistolet,fusil,arc,fleche,hache,lance,poignard | waffe,waffen,schwert,schwerter,schild,pistole,gewehr,bogen,pfeil,axt,speer,dolch | arma,armas,espada,espadas,escudo,pistola,rifle,arco,flecha,hacha,lanza,daga | arma,armi,spada,spade,scudo,pistola,fucile,arco,freccia,ascia,lancia,pugnale | arma,armas,espada,escudo,pistola,rifle,arco,flecha,machado,lanca | 武器,剣,盾,銃,弓 | 武器,剑,盾,枪,弓
ball | object | ball,balls,soccer,football,soccer ball,basketball,tennis,golf,sport,sports,messi | ballon,balle,football,foot,basket,tennis,golf,sport | ball,balle,fussball,basketball,tennis,golf,sport | balon,pelota,futbol,baloncesto,tenis,golf,deporte | palla,pallone,calcio,pallacanestro,tennis,golf,sport | bola,futebol,basquete,tenis,golfe,esporte | ボール,サッカー,スポーツ | 球,足球,篮球,运动
puzzle | object | puzzle,puzzles,rubik's cube,rubiks cube,rubik cube,cube,cubes,dice | puzzle,casse-tete,rubik's cube,cube,cubes,des | puzzle,ratsel,zauberwurfel,wurfel | rompecabezas,puzzle,cubo de rubik,cubo,dados | puzzle,rompicapo,cubo di rubik,cubo,dadi | quebra-cabeca,cubo magico,cubo,dados | パズル,ルービックキューブ,キューブ | 拼图,魔方,立方体
money | object | money,coin,coins,gold,golden,treasure,cash,dollar,dollars,wealth,rich | argent,piece,pieces,or,dore,doree,tresor,richesse,riche | geld,munze,munzen,gold,golden,schatz,reichtum,reich | dinero,moneda,monedas,oro,dorado,tesoro,riqueza,rico | soldi,denaro,moneta,monete,oro,dorato,tesoro,ricchezza,ricco | dinheiro,moeda,moedas,ouro,dourado,tesouro,riqueza,rico | お金,金,コイン,宝 | 钱,金币,金,宝藏
crypto | object | crypto,cryptocurrency,bitcoin,ethereum,blockchain,token,tokens,nft,nfts,web3,mining,miner,witness,witnesses,hardfork,hard fork,tge,ico,defi,wallet,pixa,pxs,steem,hive,dao | crypto,cryptomonnaie,bitcoin,blockchain,jeton,jetons,nft,minage,temoin | krypto,kryptowahrung,bitcoin,blockchain,token,nft,mining,zeuge | cripto,criptomoneda,bitcoin,blockchain,ficha,nft,mineria,testigo | cripto,criptovaluta,bitcoin,blockchain,gettone,nft,mining,testimone | cripto,criptomoeda,bitcoin,blockchain,token,nft,mineracao | 仮想通貨,ビットコイン,ブロックチェーン | 加密货币,比特币,区块链
text | style | text,words,letters,lettering,typography,logo,banner,announcement,quote,screenshot,chart,graph,diagram,infographic | texte,mots,lettres,typographie,logo,panneau,banniere,annonce,citation,capture d'ecran,graphique | text,worter,buchstaben,typografie,logo,schild,banner,ankundigung,zitat,bildschirmfoto,diagramm | texto,palabras,letras,tipografia,logo,cartel,pancarta,anuncio,cita,captura,grafico | testo,parole,lettere,tipografia,logo,cartello,striscione,annuncio,citazione,screenshot,grafico | texto,palavras,letras,tipografia,logo,placa,anuncio,citacao,captura,grafico | 文字,テキスト,ロゴ,看板 | 文字,文本,标志,招牌
abstract | style | abstract,geometric,pattern,patterns,shapes,fractal,psychedelic,kaleidoscope,optical illusion | abstrait,abstraite,geometrique,motif,motifs,formes,fractale,psychedelique | abstrakt,geometrisch,muster,formen,fraktal,psychedelisch | abstracto,geometrico,patron,formas,fractal,psicodelico | astratto,geometrico,motivo,forme,frattale,psichedelico | abstrato,geometrico,padrao,formas,fractal,psicodelico | 抽象,幾何学,模様 | 抽象,几何,图案
isometric | style | isometric,isometry,diorama,3d,voxel | isometrique,diorama,voxel | isometrisch,diorama,voxel | isometrico,diorama,voxel | isometrico,diorama,voxel | isometrico,diorama,voxel | アイソメトリック | 等距
retro | style | retro,vintage,old school,oldschool,80s,90s,y2k,nostalgia,nostalgic,classic | retro,vintage,annees 80,annees 90,nostalgie,nostalgique | retro,vintage,80er,90er,nostalgie,nostalgisch | retro,vintage,anos 80,anos 90,nostalgia | retro,vintage,anni 80,anni 90,nostalgia | retro,vintage,anos 80,anos 90,nostalgia | レトロ,ヴィンテージ | 复古,怀旧
cyberpunk | style | cyberpunk,sci-fi,scifi,science fiction,futuristic,neon city,dystopia,synthwave,vaporwave,matrix | cyberpunk,science-fiction,futuriste,dystopie | cyberpunk,science-fiction,futuristisch,dystopie | cyberpunk,ciencia ficcion,futurista,distopia | cyberpunk,fantascienza,futuristico,distopia | cyberpunk,ficcao cientifica,futurista,distopia | サイバーパンク,SF,未来 | 赛博朋克,科幻,未来
fantasy | style | fantasy,magic,magical,fairy,fairies,fairy tale,myth,mythology,mythical,legend,elf,elves,dwarf,goblin,orc | fantastique,fantasy,magie,magique,fee,fees,conte,mythe,mythologie,legende,elfe | fantasy,magie,magisch,fee,feen,marchen,mythos,mythologie,legende,elf,zwerg | fantasia,magia,magico,hada,hadas,cuento,mito,mitologia,leyenda,elfo | fantasy,magia,magico,fata,fate,fiaba,mito,mitologia,leggenda,elfo | fantasia,magia,magico,fada,fadas,conto,mito,mitologia,lenda,elfo | ファンタジー,魔法,妖精,神話 | 奇幻,魔法,仙女,神话
horror | style | horror,scary,creepy,spooky,gothic,goth,blood,gore | horreur,effrayant,lugubre,gothique,sang | horror,gruselig,unheimlich,gotisch,blut | horror,terror,aterrador,espeluznante,gotico,sangre | horror,orrore,spaventoso,inquietante,gotico,sangue | horror,terror,assustador,gotico,sangue | ホラー,怖い,ゴシック | 恐怖,可怕,哥特
cute | style | cute,kawaii,adorable,chibi | mignon,mignonne,adorable,kawaii,chou | suss,niedlich,kawaii,goldig | lindo,linda,mono,adorable,kawaii,tierno | carino,carina,adorabile,kawaii,tenero | fofo,fofa,lindo,kawaii | かわいい,可愛い,カワイイ | 可爱,萌
love | | love,heart,hearts,romance,romantic,kiss,valentine | amour,coeur,coeurs,romance,romantique,bisou,baiser,saint-valentin,amoureuse,amoureux | liebe,herz,herzen,romantik,romantisch,kuss,valentinstag | amor,corazon,corazones,romance,romantico,beso,san valentin | amore,cuore,cuori,romantico,bacio,san valentino | amor,coracao,coracoes,romance,romantico,beijo | 愛,ハート,恋 | 爱,爱心,浪漫
halloween | event | halloween,pumpkin,pumpkins,jack-o-lantern,trick or treat | halloween,citrouille,citrouilles | halloween,kurbis,kurbisse | halloween,calabaza,calabazas | halloween,zucca,zucche | halloween,abobora | ハロウィン,かぼちゃ | 万圣节,南瓜
christmas | event | christmas,xmas,santa,santa claus,christmas tree,reindeer,gifts,presents | noel,pere noel,sapin de noel,cadeaux | weihnachten,weihnachtsmann,tannenbaum,weihnachtsbaum,geschenke | navidad,papa noel,arbol de navidad,regalos | natale,babbo natale,albero di natale,regali | natal,papai noel,arvore de natal,presentes | クリスマス,サンタ | 圣诞节,圣诞老人,圣诞树
birthday | event | birthday,birthdays,party,parties,party hat,celebration,balloons,confetti,cake | anniversaire,fete,fetes,chapeau de fete,ballons,confettis | geburtstag,party,feier,partyhut,luftballons,konfetti | cumpleanos,fiesta,fiestas,globos,confeti | compleanno,festa,feste,palloncini,coriandoli | aniversario,festa,festas,baloes,confete | 誕生日,パーティー | 生日,派对,聚会
work | | work,working,office,job,business,meeting,boss,coworking | travail,travailler,bureau,boulot,reunion,patron | arbeit,arbeiten,buro,job,besprechung,chef | trabajo,trabajar,oficina,reunion,jefe | lavoro,lavorare,ufficio,riunione,capo | trabalho,trabalhar,escritorio,reuniao,chefe | 仕事,オフィス | 工作,办公室
japan | place | japan,japanese,tokyo,kyoto,osaka,mount fuji,fuji,fujisan,shinkansen,sakura,pagoda | japon,japonais,japonaise,tokyo | japan,japanisch,tokio | japon,japones,tokio | giappone,giapponese,tokyo | japao,japones,toquio | 日本,東京,京都,富士山 | 日本,东京,京都
china | place | china,chinese,beijing,shanghai,great wall,lantern,lanterns | chine,chinois,chinoise,pekin,lanterne,lanternes | china,chinesisch,peking,laterne,laternen | china,chino,china,pekin,linterna | cina,cinese,pechino,lanterna,lanterne | china,chines,pequim,lanterna | 中国,北京,提灯 | 中国,北京,灯笼
switzerland | place | switzerland,swiss,zurich,geneva,lucerne,bern,alps,lake lucerne,stoos,fluelen,erstfeld,vierwaldstattersee,viervaldstattersee | suisse,suisses,zurich,geneve,lucerne,berne,alpes | schweiz,schweizer,zurich,genf,luzern,bern,alpen,vierwaldstattersee | suiza,suizo,zurich,ginebra,lucerna,berna,alpes | svizzera,svizzero,zurigo,ginevra,lucerna,berna,alpi | suica,suico,zurique,genebra,lucerna,berna,alpes | スイス,チューリッヒ | 瑞士,苏黎世
spain | place | spain,spanish,barcelona,bcn,madrid,barceloneta,el born,catalonia,jamon | espagne,espagnol,barcelone,madrid | spanien,spanisch,barcelona,madrid | espana,espanol,barcelona,madrid,cataluna | spagna,spagnolo,barcellona,madrid | espanha,espanhol,barcelona,madri | スペイン,バルセロナ | 西班牙,巴塞罗那
france | place | france,french,paris,eiffel tower | france,francais,francaise,paris,tour eiffel | frankreich,franzosisch,paris,eiffelturm | francia,frances,paris,torre eiffel | francia,francese,parigi,torre eiffel | franca,frances,paris,torre eiffel | フランス,パリ | 法国,巴黎
italy | place | italy,italian,rome,venice,florence,milan | italie,italien,italienne,rome,venise,florence,milan | italien,italienisch,rom,venedig,florenz,mailand | italia,italiano,roma,venecia,florencia,milan | italia,italiano,roma,venezia,firenze,milano | italia,italiano,roma,veneza,florenca,milao | イタリア,ローマ | 意大利,罗马
slovakia | place | slovakia,slovak,bratislava,high tatras,tatras,tatra | slovaquie,slovaque,bratislava,hautes tatras | slowakei,slowakisch,bratislava,hohe tatra | eslovaquia,eslovaco,bratislava,altos tatras | slovacchia,slovacco,bratislava,alti tatra | eslovaquia,eslovaco,bratislava | スロバキア,ブラチスラバ | 斯洛伐克,布拉迪斯拉发
india | place | india,indian,taj mahal,agra,delhi,mumbai | inde,indien,indienne,taj mahal | indien,indisch,taj mahal | india,indio,taj mahal | india,indiano,taj mahal | india,indiano,taj mahal | インド,タージ・マハル | 印度,泰姬陵
usa | place | usa,america,american,united states,new york,los angeles,washington,capitol | etats-unis,amerique,americain,new york | usa,amerika,amerikanisch,vereinigte staaten,new york | estados unidos,america,americano,nueva york | stati uniti,america,americano,new york | estados unidos,america,americano,nova york | アメリカ,ニューヨーク | 美国,纽约
brazil | place | brazil,brazilian,rio,boitata | bresil,bresilien | brasilien,brasilianisch | brasil,brasileno | brasile,brasiliano | brasil,brasileiro | ブラジル | 巴西
singapore | place | singapore,merlion | singapour | singapur | singapur | singapore | singapura | シンガポール | 新加坡
`;

export interface Concept {
  id: string;
  parents: string[];
  aliases: Map<string, Set<string>>; // folded alias -> languages
}
